Repository heyhoio/heyho, pull requests merged in 2020-03, with the labels that each got.

#3 feat: including textshadow gen, bordergen & b64 convert
  layouts/default.vue
  package.json
  pages/base64-converter.vue
  pages/border-radius-generator.vue
  pages/index.vue
  pages/text-shadow-generator.vue
  yarn.lock
Labels: feat

#20 feat: add test structure and tests
  .prettierrc
  jest.config.js
  package-lock.json
  package.json
  test/Logo.spec.js
  test/jest.setup.js
  test/pages/about.spec.js
  test/pages/box-shadow-generator.spec.js
  test/pages/color-picker.spec.js
  test/pages/credit-card-generator.spec.js
  test/pages/css-filters.spec.js
  test/pages/index.spec.js
  test/pages/regex-replace-viewer.spec.js
  yarn.lock
Labels: feat

#22 feat: create git actions
  .github/workflows/blank.yml
Labels: feat

#25 refactor: base 64 generator
  layouts/default.vue
  package.json
  pages/base64-converter.vue
  pages/index.vue
  utils/base64.js
  yarn.lock
Labels: refactor

#26 refactor: index message
  pages/index.vue
Labels: refactor

#16 feat: add contributors' names
  pages/about.vue
Labels: feat

#17 fix: implement title smartly
  nuxt.config.js
  pages/about.vue
  pages/box-shadow-generator.vue
  pages/color-picker.vue
  pages/credit-card-generator.vue
  pages/css-filters.vue
  pages/index.vue
  pages/regex-replace-viewer.vue
Labels: fix
